### ISSUE TITLE
Adding multiple ear tags shows animal multiple times

### ISSUE THREAD

**Issue by blackundertone** [farmOS-legacy/farm_asset#1] opened 2016-10-01 09:54 UTC
In the animals menu [/farmos/farm/assets/animals], if i add multiple ear tags to an animal that animal shows multiple times in the list.

See attached. Cow 209 had a calf tag 3, which was replaced with adult tag 209 and cow was renamed. This caused it to show twice. I added another tag 111 to check, and it now shows 3 times in the Animals list.

![screenshot_2016-10-01-19-51-05](https://cloud.githubusercontent.com/assets/11969840/19013306/79a88456-8810-11e6-88ae-47645cc5516f.png)

**Comment by mstenta** [comment] 2016-10-01 17:51
Thanks for the bug report @blackundertone !

I think this may have been fixed in the last release.  Are you using 7.x-1.0-beta12?  Here is the original issue on drupal.org: https://www.drupal.org/node/2707083

**Comment by blackundertone** [comment] 2016-10-03 06:38
Hi Michael,

Thanks - that does look identical to the issue I see, however I am
running 7.x-1.0-beta12
so im not sure why it may have regressed ?

I checked the file and it appears to be the latest from github 7cfeb64

/opt/farmos/farm-7.x-1.0-beta12/profiles/farm/modules/farm/farm_livestock/farm_livestock.views_default.inc

**Comment by mstenta** [comment] 2016-10-03 13:15
Hmm - it's possible that you've discovered a similar but different issue.

Another possibility is that your farm_animals View is overridden, so it didn't receive the bugfix when you updated.  Questions: did you start with beta12?  Or did you upgrade from an earlier version?  Most importantly: did you modify or customize the farm_animals View at all yourself?

It's easy enough to find out if the farm_animals View is modified.  You need to enable the Diff module, and examine the state of the farm_livestock feature module in /admin/structure/features - it will say "Overridden" next to it if so.

If none of the above is true - then it may be a different issue.

**Comment by blackundertone** [comment] 2016-10-04 09:21
![farmier_farmos_duplicateanimal](https://cloud.githubusercontent.com/assets/11969840/19069010/b01ab308-8a70-11e6-8455-9a35deffd545.png)
I reproduced the error on the Farmier Instance that I just signed up for.

To reproduce:
1. Create a new Animal with an ear tag and save
2. Edit the animal & add another ear tag
3. View the list of animals - and it is displayed twice (attached).

Cheers,
Ash

**Comment by mstenta** [comment] 2016-10-04 12:24
Ah ok thanks Ash! I will take a look in the Farmier instance. Thanks for reproducing it for me!

**Comment by mstenta** [comment] 2016-10-04 12:44
Yea it looks like the same issue... weird because the fix did work previously. Not sure why it's not working now. I will have to dig deeper.

In the meantime, I removed the "Sort by ID" and "Filter by ID" options - which fixes the issue temporarily in your Farmier site. I will put together a more permanent fix, which hopefully will restore those two features, but for now at least your animals aren't showing more than once!

**Comment by mstenta** [comment] 2016-10-04 12:47
I've reopened the original issue in drupal.org: https://www.drupal.org/node/2707083

Thanks again for bringing this to my attention, Ash! I'm going to close this one and focus further debugging in the drupal.org issue. I've linked to this from there as well.

**Closed as completed by mstenta** 2016-10-04 12:47 UTC

**Comment by blackundertone** [comment] 2016-10-04 22:33
Great - thanks Mike, looks good now.
